### ISSUE TITLE
New version with axum 0.7 support

### ISSUE THREAD

**Issue by garlic-hub** [programatik29/axum-server#101]
Hello it looks like axum-server has axum 0.7 support now, as well as some other fixes. Can we cut a new tag? Probably a 0.6 since axum has had breaking changes

**Comment by GPSnoopy** [comment]
Yes, please. `axum-server` is the last package blocking our migration to the latest versions of `axum`, `http`, `hyper`, and co.

**Comment by DerPlayer2001** [comment]
After looking at previous Releases I think it’s possible that only @programatik29 has the appropriate Permissions… But he doesn’t seem to be very aktive, not shure how to best get in touch with him...

**Comment by abs0luty** [comment]
Everything seems to work now, so I will probably create a new release in 1-2 days.

**Comment by Madoshakalaka** [comment]
@abs0luty thanks for the work. Also I just tested the master branch with my project ising axum 0.7.2. It worked well.
