### ISSUE TITLE
Update hyper dependency version

### ISSUE THREAD

**Issue by damooo** [programatik29/axum-server#123]
Thanks for great work.

Currently hyper dependency version is mentioned as "1.0.1". This does not allow to use latest version like "1.4.0", etc. If we signify only minor version like "1.0", it can use "1.x" versions. Same with few other http crates.

**Comment by NOBLES5E** [comment]
I noticed this repository hasn't been very active recently. To address this and other pending issues, I've created a new crate called [`axum-serveplus`](https://github.com/NOBLES5E/axum-serveplus) which includes recent bug fixes and updated dependencies.

If development on this original crate resumes, we can certainly look at implementing these dependency updates. In the meantime, `axum-serveplus` may be a good option for those wanting the latest fixes and dependency versions.
