### ISSUE TITLE
Memory leak in server

### ISSUE THREAD

**Issue by andrewhickman** [programatik29/axum-server#13]
Hi, I was reading through the code and I noticed this list of connections

https://github.com/programatik29/axum-server/blob/8574eaa2717803949877e8b00a26ea6a6f9604d9/src/server/http_server.rs#L116

it seems to grow every time the server accepts a connection and is never cleared out, so it might be an issue for a long-running server

I tried making lots of requests to the hello_world example server and after ~500,000 requests memory usage was about 1 GB

**Comment by programatik29** [comment]
I will fix that today.
