### ISSUE TITLE
tls-rustls with axum-sever version 0.7.1

### ISSUE THREAD

**Issue by AriesChengYan** [programatik29/axum-server#140]
error: failed to run custom build command for `aws-lc-sys v0.20.1`

Caused by:
  process didn't exit successfully: `~\target\debug\build\aws-lc-sys-265ef571af8060ee\build-script-main` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=AWS_LC_SYS_NO_PREFIX
  cargo:rerun-if-env-changed=AWS_LC_SYS_INTERNAL_BINDGEN
  cargo:rerun-if-env-changed=AWS_LC_SYS_EXTERNAL_BINDGEN
  cargo:rerun-if-env-changed=AWS_LC_SYS_NO_ASM
  cargo:rerun-if-env-changed=AWS_LC_SYS_CMAKE_BUILDER
  cargo:rerun-if-env-changed=AWS_LC_SYS_STATIC
  cargo:rerun-if-env-changed=CMAKE

  --- stderr
  Consider setting `AWS_LC_SYS_NO_ASM` in the environment for development builds.See User Guide about the limitations: https://aws.github.io/aws-lc-rs/index.html
  Missing dependency: nasm
  thread 'main' panicked at ~\aws-lc-sys-0.20.1\builder/main.rs:302:40:
  called `Result::unwrap()` on an `Err` value: "Required build dependency is missing. Halting build."
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by daxpedda** [comment]
See the [build requirement guide for `aws-lc-rs`](https://aws.github.io/aws-lc-rs/requirements/index.html).
