### ISSUE TITLE
How to customize multiple TLS versions？

### ISSUE THREAD

**Issue by dslchd** [programatik29/axum-server#144]
Hello everyone, I want the server to support TLS 1.2, TLS 1.3 at the same time, which API should I use, or what method should I use to make the service support multiple versions of TLS at the same time?

I didn't find any workaround from the example.

**Comment by daxpedda** [comment]
Could you enable [Rustls `tls12`](https://docs.rs/crate/rustls/0.23.12/features#tls12) and see if that solves your problem?

Maybe we should consider enabling this by default as well (`rustls` does it) with `tls-rustls`.

**Comment by dslchd** [comment]
> Could you enable [Rustls `tls12`](https://docs.rs/crate/rustls/0.23.12/features#tls12) and see if that solves your problem?您可以启用[Rustls `tls12`](https://docs.rs/crate/rustls/0.23.12/features#tls12)看看是否能解决您的问题？
> 
> ~Maybe we should consider enabling this by default as well (`rustls` does it) with `tls-rustls`.也许我们应该考虑使用`tls-rustls`默认启用此功能（ `rustls`就是这样做的）。~ EDIT: Indeed, #130 addresses this.编辑：确实， #130 解决这个问题。
Thank you very much for your answer, I'm going to go and look into your suggestion
