### ISSUE TITLE
Hybrid server with axum+tonic

### ISSUE THREAD

**Issue by pixelspark** [programatik29/axum-server#22]
I am trying to build a hybrid HTTP + gRPC server using Axum and Tonic following [this example](https://github.com/snoyberg/tonic-example/blob/master/src/bin/server-hybrid.rs). I am struggling a bit however on how to combine this with axum-server to have both over TLS:

````rust
let app = /* axum app */;
let grpc_service = tonic::transport::Server::builder().add_service(/* some gRPC service */).into_service();
let hybrid_make_service = hybrid(app.into_make_service(), grpc_service);

// This works fine
axum::Server::bind(&sc.bind_address).serve(hybrid_make_service).await?;

// This I can't get right...
axum_server::bind_rustls(sc.bind_address.to_string())
				.private_key_file(tls_key_path)
				.certificate_file(tls_cert_path)
				.serve(hybrid_make_service)
				.await?;
````

The issue seems to be that axum_server requires a 'Service' whereas the regular 'bind' accepts some sort of 'IntoService' (and the `hybrid` function, as well as grpc_service, create this). Any ideas?

**Comment by pixelspark** [comment]
See also here: https://www.fpcomplete.com/blog/axum-hyper-tonic-tower-part4/

**Comment by programatik29** [comment]
You need to pass a `Service` that is `Clone`.

All `Service`s provided by `axum` are `Clone` by default.

[`RouterService`] implements `Clone` if service wrapped in it implements it. So you need to make sure *wrapped gRPC service* is `Clone`.

[`RouterService`]: https://docs.rs/tonic/0.5.2/tonic/transport/server/struct.RouterService.html

**Comment by programatik29** [comment]
Let me know if [this](https://github.com/programatik29/axum-tonic-server) helps.

**Comment by pixelspark** [comment]
> Let me know if [this](https://github.com/programatik29/axum-tonic-server) helps.

Absolutely, this works like a charm! Thanks so much (and indeed, good idea to add this example, should probably end up in this repo?)

**Comment by programatik29** [comment]
@itsyaasir I removed it because it wasn't up to date. I will write a new example for the new api and let you know when its done.

**Comment by itsyaasir** [comment]
> @itsyaasir I removed it because it wasn't up to date. I will write a new example for the new api and let you know when its done.

Thank you , I appreciate that

**Comment by programatik29** [comment]
@itsyaasir Let me know if [this example](https://github.com/programatik29/axum-tonic-server) works for you.

**Comment by itsyaasir** [comment]
> @itsyaasir Let me know if [this example](https://github.com/programatik29/axum-tonic-server) works for you.

Absolutely, it worked, I got the general idea of the implementation. Thank you
