### ISSUE TITLE
How to support https and http dual protocol with rewrite-minimal branch

### ISSUE THREAD

**Issue by c5soft** [programatik29/axum-server#26]
hi, Eray, i've tested your recent posted rewrite-minimal redesign version, it works! but i noticed one problem: there is no way to make a single server to provide https and http dual protocol like version 0.2.5. This is a must-have feature, please please conside it.

**Comment by programatik29** [comment]
I think current lower level approach is better.

With this new design, some features are removed but you can implement them yourself. For example, spawn one http server task and spawn one https server task then join them.

**Comment by c5soft** [comment]
That's greet, but i'd prefer something out-of-box. Thanks.

**Comment by c5soft** [comment]
http_and_https.rs is very good example. Thanks.
