### ISSUE TITLE
Why have a different API for graceful shutdown?

### ISSUE THREAD

**Issue by jplatte** [programatik29/axum-server#35]
Why do you have to obtain a handle and spawn a task with axum-server instead of having the same API as hyper (`Server::with_graceful_shutdown`)?

**Comment by programatik29** [comment]
It is just a different design decision. This library is a high level implementation of low level hyper api rather than a wrapper around existing high level hyper server.

**Comment by jplatte** [comment]
Alright. A real-world example might be nice because I was really confused at first. But the main question was answered, so I'll close this.
