### ISSUE TITLE
Graceful shutdown doesn't include upgraded connections

### ISSUE THREAD

**Issue by jeremycline** [programatik29/axum-server#40]
Hi,

When using Axum with WebSockets, I noticed having an open WebSocket doesn't stop the server from shutting down gracefully. [Here's a demo repository](https://github.com/jeremycline/axum-graceful-shutdown/blob/main/src/main.rs). 

My expectation was that the demo would remain running for 30 seconds, printing "beep" every second until the graceful shutdown timeout is reached.

I'm not terribly familiar with Hyper so I don't immediately see a fix, so I figured I'd start with an issue. I'm happy to work on a fix, however.

**Comment by programatik29** [comment]
The reason is `hyper`s http future is terminated after upgrade response.

Take a look at [`serve_connection`](https://docs.rs/hyper/latest/hyper/server/conn/struct.Http.html#method.serve_connection). This future terminates even if there is an upgraded connection.

**Comment by jeremycline** [comment]
FWIW the way I solved this (and I'm embarrassed it took me a while to think of) is to just stash a channel handle in my shared state structure and each WebSocket takes a clone, just like the [graceful shutdown tutorial for tokio](https://tokio.rs/tokio/topics/shutdown). After the server shuts down the state gets dropped so it'll hang out until the WebSockets are done.
