### ISSUE TITLE
Obtaining actual bound listener port? 

### ISSUE THREAD

**Issue by josb** [programatik29/axum-server#46]
When the `SockAddr` `bind` port is specified as 0, the kernel picks a random port to listen on. How does one gain access to this bound listener port? `axum` allows access to https://docs.rs/hyper/0.14.18/hyper/server/struct.Server.html#method.local_addr, how can one obtain the equivalent information using `axum-server`?

**Comment by programatik29** [comment]
You can use `Handle::listening` method.

**Comment by josb** [comment]
Unfortunately this cannot be called from a non-`async` context, whereas `local_addr()` can, so I'm not sure how to make this work.

**Comment by josb** [comment]
I've managed to [implement](https://github.com/getsentry/symbolicator/pull/829/commits/105a3af1a5ca1cbfe685fe3fb556de70567b71b5) this, but it feels racy. Is there a better way?

**Comment by programatik29** [comment]
Should be fine. By design you can't bind first then do something then start the server. Binding and starting the server must happen in order.

**Comment by josb** [comment]
Makes sense. Thanks for the review, @programatik29!
