### ISSUE TITLE
Add `Server::acceptor_mut`

### ISSUE THREAD

**Issue by daxpedda** [programatik29/axum-server#49]
I have a use-case where I implemented my own `Accept`or. Additionally I would like to add more configuration options, but currently it's not possible to modify the acceptor once wrapped in `Server`. My proposal is to add a method that can return a mutable reference to the `Acceptor` called `Server::acceptor_mut()`, bikeshedding welcome.

The alternative is to use the `Server::acceptor()` to add a pre-configured `Accept`or, but the user-ergonomics are slightly worse that way.
Happy to make a PR if this is approved.

**Comment by programatik29** [comment]
Good idea. It would also be nice to add more methods like `map` to make working with `Acceptor` easier.
