### ISSUE TITLE
Document how to use a `Service` factory for `Server::serve()`

### ISSUE THREAD

**Issue by daxpedda** [programatik29/axum-server#52]
I would like to wrap a user supplied app, like a `Router`, for that purpose I would like to use [`ServiceBuilder`](https://docs.rs/tower/0.4.13/tower/struct.ServiceBuilder.html).

The issue is that [`Server::serve()`](https://docs.rs/axum-server/latest/axum_server/struct.Server.html#method.serve) needs a service factory, like what can be produced with [`Router::into_make_service()`](https://docs.rs/axum/0.5.13/axum/routing/struct.Router.html#method.into_make_service), which isn't available for `ServiceBuilder`.

The solution I found is wrapping it in [`Shared`](https://docs.rs/tower/0.4.13/tower/make/struct.Shared.html). I believe some documentation in `axum-server` would help. 

See https://github.com/tokio-rs/axum/issues/1203 for the original problem.

**Comment by programatik29** [comment]
I will add it for next release.

**Comment by daxpedda** [comment]
Added in https://github.com/programatik29/axum-server/commit/1a68546ed34ebd8f003c837855ca0101be32205.
