### ISSUE TITLE
What is the best way to use different configs based on the connection ?

### ISSUE THREAD

**Issue by dvtkrlbs** [programatik29/axum-server#57]
My use case is I need to use different server configs based on the SNI value (multiple domains each with different certificates and client certificate authentication requirements). Rustls offers an acceptor for this use case. I can see that there is an Accept trait for similiar use case. However looking at the code the default RustlsAcceptor uses a RustlsAcceptorFuture which actually setups the rustls. Should I make my own Acceptor if so do I need to replicate the behaviour of RustlsAcceptorFuture ?

**Comment by programatik29** [comment]
Take a look at [`RustlsConfig::from_config`] it might just work for you.

If you want to implement [`Accept`] trait I suggest using [`BoxFuture`] as `Future` return type. Then you can return a normal async block like `Box::pin(async move {})`.

[`RustlsConfig::from_config`]: https://docs.rs/axum-server/0.4/axum_server/tls_rustls/struct.RustlsConfig.html#method.from_config
[`Accept`]: https://docs.rs/axum-server/0.4/axum_server/accept/trait.Accept.html
[`BoxFuture`]: https://docs.rs/futures-util/0.3/futures_util/future/type.BoxFuture.html
