### ISSUE TITLE
HTTP/2 with rustls-acme

### ISSUE THREAD

**Issue by nicolaspernoud** [programatik29/axum-server#62]
Hello,

I use rustls-acme to create automatically Let's Encrypt certificates like in https://github.com/FlorianUekermann/rustls-acme/blob/main/examples/low_level_axum.rs . It works very well, but the server seems not to respond with HTTP/2, even if the http2 feature is enabled in axum.

How can I enable HTTP/2 ?

Thanks and best regards.

**Comment by programatik29** [comment]
This should probably be documented.

**Comment by nicolaspernoud** [comment]
Hello,
That does the trick perfectly, thanks a lot.
I'll reach out to the rustls-acme maintainer to see for the documentation.
Best regards.

**Comment by programatik29** [comment]
I mean it should be documented in this crate.

**Comment by nicolaspernoud** [comment]
Ah, OK, thanks !
