### ISSUE TITLE
add rationale to docs 

### ISSUE THREAD

**Issue by matthiasdebernardini** [programatik29/axum-server#70]
I am curious what the main benefit to running this server instead of the default that axum crate uses.

Why should someone consider using this crate in their web API?

**Comment by programatik29** [comment]
Main reason is to use TLS easily and efficiently. Limitations of `hyper::server::Server` makes it really hard and tricky to efficiently use TLS. This crate solves the problem by providing alternative high level (hyper) server which has a different API.
