### ISSUE TITLE
[Question] Is there a reload for `addr:port`? 

### ISSUE THREAD

**Issue by Geobert** [programatik29/axum-server#72]
I’ve read the reload example which is fantastic for TLS certificate renewal, and it made me wondering if we can do something similar for the binding addr? (In case of configuration change)

**Comment by programatik29** [comment]
Create a new server with the new `addr:port`. Then shutdown the old server. A utility can make this process easier but I think it is easy enough.

**Comment by Geobert** [comment]
OK, that what I was aiming for, but just to be sure I wasn’t missing out something :)

Thanks!
