### ISSUE TITLE
`h2` always reported in `alpn_protocols`

### ISSUE THREAD

**Issue by Diggsey** [programatik29/axum-server#80]
https://github.com/programatik29/axum-server/blob/86bc6e7311959285ff00815843a8d702affe51d9/src/tls_rustls/mod.rs#L278

This is wrong as the axum server doesn't necessarily support http2.

**Comment by daxpedda** [comment]
I don't think there is currently a way for `axum-server` to not serve both protocols HTTP/2.
Internally [`Builder::serve_connection_with_upgrades()`](https://docs.rs/hyper-util/0.1.6/hyper_util/server/conn/auto/struct.Builder.html#method.serve_connection_with_upgrades) is used, so e.g. no matter if you use [`Builder::http2_only()`](https://docs.rs/hyper-util/0.1.6/hyper_util/server/conn/auto/struct.Builder.html#method.http2_only), both HTTP/1 and HTTP/2 will be served.

Let me know if I'm wrong about that.
