### ISSUE TITLE
[FR]: support `app.into_make_service_with_connect_info::<SocketAddr>()`

### ISSUE THREAD

**Issue by mokeyish** [programatik29/axum-server#91]
Hello, thanks for your nice library！

Currently,  `app.into_make_service_with_connect_info::<SocketAddr>()` is not support.

```rs

use axum::{
    routing::get,
    Router,
};

let app = Router::new().route("/", get(|| async { "Hi!" }));

axum::Server::bind(&"0.0.0.0:3000".parse().unwrap())
    .serve(app.into_make_service())
    .await
    .expect("server failed");

```

https://docs.rs/axum/latest/src/axum/routing/mod.rs.html#384-388

**Comment by programatik29** [comment]
Can you provide a reproducible example of it not working?

Currently you can get connection info as shown in this [example](https://github.com/programatik29/axum-server/blob/v0.5.1/examples/remote_address.rs).

**Comment by mokeyish** [comment]
thanks, that worked.
